/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* src = "ackor.v:1" *)
module ackor(ack0, ack1, ack2, ack3, ack);
  wire _0_;
  wire _1_;
  (* src = "ackor.v:1" *)
  output ack;
  (* src = "ackor.v:1" *)
  input ack0;
  (* src = "ackor.v:1" *)
  input ack1;
  (* src = "ackor.v:1" *)
  input ack2;
  (* src = "ackor.v:1" *)
  input ack3;
  assign _0_ = ack1 | ack0;
  assign _1_ = _0_ | ack2;
  assign ack = _1_ | ack3;
endmodule

(* src = "arb.v:1" *)
module arb(req0, req1, req2, req3, ack0, ack1, ack2, ack3, clk, rst);
  (* src = "arb.v:5" *)
  wire _000_;
  (* src = "arb.v:5" *)
  wire _001_;
  (* src = "arb.v:5" *)
  wire _002_;
  (* src = "arb.v:5" *)
  wire _003_;
  (* src = "arb.v:5" *)
  wire [2:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  (* src = "arb.v:1" *)
  output ack0;
  reg ack0;
  (* src = "arb.v:1" *)
  output ack1;
  reg ack1;
  (* src = "arb.v:1" *)
  output ack2;
  reg ack2;
  (* src = "arb.v:1" *)
  output ack3;
  reg ack3;
  (* src = "arb.v:1" *)
  input clk;
  (* src = "arb.v:3" *)
  reg [2:0] nstate;
  (* src = "arb.v:1" *)
  input req0;
  (* src = "arb.v:1" *)
  input req1;
  (* src = "arb.v:1" *)
  input req2;
  (* src = "arb.v:1" *)
  input req3;
  (* src = "arb.v:1" *)
  input rst;
  (* src = "arb.v:3" *)
  reg [2:0] state;
  assign _021_ = ~(state[1] & state[0]);
  assign _022_ = ~(_021_ | state[2]);
  assign _023_ = state[0] | ~(state[1]);
  assign _024_ = ~(_023_ | state[2]);
  assign _025_ = ~(_024_ | _022_);
  assign _026_ = ~state[2];
  assign _027_ = state[1] | ~(state[0]);
  assign _028_ = _027_ | ~(_026_);
  assign _029_ = state[1] | state[0];
  assign _030_ = _029_ | ~(_026_);
  assign _031_ = ~(_030_ & _028_);
  assign _032_ = _031_ | ~(_025_);
  assign _033_ = req0 | ~(req1);
  assign _034_ = ~(_033_ | req3);
  assign _035_ = _034_ & ~(req2);
  assign _036_ = ~((_034_ & _022_) | (_024_ & _035_));
  assign _037_ = ~req1;
  assign _038_ = ~((_030_ | _033_) & (_028_ | _037_));
  assign _039_ = _038_ | ~(_036_);
  assign _001_ = _032_ ? _039_ : ack1;
  assign _040_ = ~_022_;
  assign _041_ = ~_024_;
  assign _042_ = req3 | ~(req0);
  assign _043_ = ~req2;
  assign _044_ = _042_ | ~(_043_);
  assign _045_ = ~((_042_ | _040_) & (_041_ | _044_));
  assign _046_ = ~req0;
  assign _047_ = _044_ | ~(_037_);
  assign _048_ = ~((_030_ | _046_) & (_028_ | _047_));
  assign _049_ = _048_ | _045_;
  assign _000_ = _032_ ? _049_ : ack0;
  assign _050_ = ~nstate[0];
  assign _051_ = ~req3;
  assign _052_ = ~((req1 | req2) & nstate[0]);
  assign _053_ = req0 ? _050_ : _052_;
  assign _054_ = req3 ? _050_ : _053_;
  assign _055_ = ~((_046_ & _037_) | nstate[0]);
  assign _056_ = req3 ? _050_ : _055_;
  assign _057_ = req2 ? _050_ : _056_;
  assign _058_ = ~((_054_ | _040_) & (_041_ | _057_));
  assign _059_ = ~((req3 | req0) & nstate[0]);
  assign _060_ = req2 ? _050_ : _059_;
  assign _061_ = req1 ? _050_ : _060_;
  assign _062_ = ~((_051_ & _043_) | nstate[0]);
  assign _063_ = req1 ? _050_ : _062_;
  assign _064_ = req0 ? _050_ : _063_;
  assign _065_ = ~((_061_ | _028_) & (_030_ | _064_));
  assign _066_ = _065_ | _058_;
  assign _004_[0] = _032_ ? _066_ : nstate[0];
  assign _067_ = ~nstate[1];
  assign _068_ = ~((req1 | req2) & nstate[1]);
  assign _069_ = req0 ? _067_ : _068_;
  assign _070_ = req3 ? _067_ : _069_;
  assign _071_ = ~((_046_ & _037_) | nstate[1]);
  assign _072_ = req3 ? _067_ : _071_;
  assign _073_ = req2 ? _067_ : _072_;
  assign _074_ = ~((_070_ | _040_) & (_041_ | _073_));
  assign _075_ = ~((_051_ & _046_) | nstate[1]);
  assign _076_ = req2 ? _067_ : _075_;
  assign _077_ = req1 ? _067_ : _076_;
  assign _078_ = ~((req3 | req2) & nstate[1]);
  assign _079_ = req1 ? _067_ : _078_;
  assign _080_ = req0 ? _067_ : _079_;
  assign _081_ = ~((_077_ | _028_) & (_030_ | _080_));
  assign _082_ = _081_ | _074_;
  assign _004_[1] = _032_ ? _082_ : nstate[1];
  assign _083_ = ~nstate[2];
  assign _084_ = ~((req1 | req2) & nstate[2]);
  assign _085_ = req0 ? _083_ : _084_;
  assign _086_ = req3 ? _083_ : _085_;
  assign _087_ = ~((req0 | req1) & nstate[2]);
  assign _088_ = req3 ? _083_ : _087_;
  assign _089_ = req2 ? _083_ : _088_;
  assign _090_ = ~((_086_ | _040_) & (_041_ | _089_));
  assign _091_ = ~((req3 | req0) & nstate[2]);
  assign _092_ = req2 ? _083_ : _091_;
  assign _093_ = req1 ? _083_ : _092_;
  assign _094_ = ~((req3 | req2) & nstate[2]);
  assign _005_ = req1 ? _083_ : _094_;
  assign _006_ = req0 ? _083_ : _005_;
  assign _007_ = ~((_093_ | _028_) & (_030_ | _006_));
  assign _008_ = _007_ | _090_;
  assign _004_[2] = _032_ ? _008_ : nstate[2];
  assign _009_ = req2 | ~(req3);
  assign _010_ = ~((_041_ | _009_) & (_040_ | _051_));
  assign _011_ = _009_ | ~(_037_);
  assign _012_ = _011_ | ~(_046_);
  assign _013_ = ~((_011_ | _028_) & (_030_ | _012_));
  assign _014_ = _013_ | _010_;
  assign _003_ = _032_ ? _014_ : ack3;
  assign _015_ = req1 | ~(req2);
  assign _016_ = _015_ | ~(_046_);
  assign _017_ = ~(_016_ | req3);
  assign _018_ = ~((_024_ & req2) | (_022_ & _017_));
  assign _019_ = ~((_015_ | _028_) & (_030_ | _016_));
  assign _020_ = _019_ | ~(_018_);
  assign _002_ = _032_ ? _020_ : ack2;
  (* src = "arb.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      ack0 <= 0;
    else
      ack0 <= _000_;
  (* src = "arb.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      ack1 <= 0;
    else
      ack1 <= _001_;
  (* src = "arb.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      ack2 <= 0;
    else
      ack2 <= _002_;
  (* src = "arb.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      ack3 <= 0;
    else
      ack3 <= _003_;
  (* src = "arb.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      state[0] <= 0;
    else
      state[0] <= nstate[0];
  (* src = "arb.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      state[1] <= 0;
    else
      state[1] <= nstate[1];
  (* src = "arb.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      state[2] <= 0;
    else
      state[2] <= nstate[2];
  (* src = "arb.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      nstate[0] <= 0;
    else
      nstate[0] <= _004_[0];
  (* src = "arb.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      nstate[1] <= 0;
    else
      nstate[1] <= _004_[1];
  (* src = "arb.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      nstate[2] <= 0;
    else
      nstate[2] <= _004_[2];
endmodule

(* src = "cb.v:1" *)
module cb(i0, i1, i2, i3, o0, o1, o2, o3, d0, d1, d2, d3);
  (* src = "cb.v:2" *)
  input [3:0] d0;
  (* src = "cb.v:2" *)
  input [3:0] d1;
  (* src = "cb.v:2" *)
  input [3:0] d2;
  (* src = "cb.v:2" *)
  input [3:0] d3;
  (* src = "cb.v:1" *)
  input [9:0] i0;
  (* src = "cb.v:1" *)
  input [9:0] i1;
  (* src = "cb.v:1" *)
  input [9:0] i2;
  (* src = "cb.v:1" *)
  input [9:0] i3;
  (* src = "cb.v:1" *)
  output [9:0] o0;
  (* src = "cb.v:1" *)
  output [9:0] o1;
  (* src = "cb.v:1" *)
  output [9:0] o2;
  (* src = "cb.v:1" *)
  output [9:0] o3;
  (* module_not_derived = 32'd1 *)
  (* src = "cb.v:4" *)
  cbsel cbsel0 (
    .d(d0),
    .i0(i0),
    .i1(i1),
    .i2(i2),
    .i3(i3),
    .o(o0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cb.v:5" *)
  cbsel cbsel1 (
    .d(d1),
    .i0(i0),
    .i1(i1),
    .i2(i2),
    .i3(i3),
    .o(o1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cb.v:6" *)
  cbsel cbsel2 (
    .d(d2),
    .i0(i0),
    .i1(i1),
    .i2(i2),
    .i3(i3),
    .o(o2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cb.v:7" *)
  cbsel cbsel3 (
    .d(d3),
    .i0(i0),
    .i1(i1),
    .i2(i2),
    .i3(i3),
    .o(o3)
  );
endmodule

(* src = "cbsel.v:1" *)
module cbsel(i0, i1, i2, i3, o, d);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  (* src = "cbsel.v:2" *)
  input [3:0] d;
  (* src = "cbsel.v:1" *)
  input [9:0] i0;
  (* src = "cbsel.v:1" *)
  input [9:0] i1;
  (* src = "cbsel.v:1" *)
  input [9:0] i2;
  (* src = "cbsel.v:1" *)
  input [9:0] i3;
  (* src = "cbsel.v:2" *)
  output [9:0] o;
  assign _00_ = d[3] & i3[0];
  assign _01_ = d[2] ? i2[0] : _00_;
  assign _02_ = d[1] ? i1[0] : _01_;
  assign o[0] = d[0] ? i0[0] : _02_;
  assign _03_ = i3[1] & d[3];
  assign _04_ = d[2] ? i2[1] : _03_;
  assign _05_ = d[1] ? i1[1] : _04_;
  assign o[1] = d[0] ? i0[1] : _05_;
  assign _06_ = i3[2] & d[3];
  assign _07_ = d[2] ? i2[2] : _06_;
  assign _08_ = d[1] ? i1[2] : _07_;
  assign o[2] = d[0] ? i0[2] : _08_;
  assign _09_ = i3[3] & d[3];
  assign _10_ = d[2] ? i2[3] : _09_;
  assign _11_ = d[1] ? i1[3] : _10_;
  assign o[3] = d[0] ? i0[3] : _11_;
  assign _12_ = i3[4] & d[3];
  assign _13_ = d[2] ? i2[4] : _12_;
  assign _14_ = d[1] ? i1[4] : _13_;
  assign o[4] = d[0] ? i0[4] : _14_;
  assign _15_ = i3[5] & d[3];
  assign _16_ = d[2] ? i2[5] : _15_;
  assign _17_ = d[1] ? i1[5] : _16_;
  assign o[5] = d[0] ? i0[5] : _17_;
  assign _18_ = i3[6] & d[3];
  assign _19_ = d[2] ? i2[6] : _18_;
  assign _20_ = d[1] ? i1[6] : _19_;
  assign o[6] = d[0] ? i0[6] : _20_;
  assign _21_ = i3[7] & d[3];
  assign _22_ = d[2] ? i2[7] : _21_;
  assign _23_ = d[1] ? i1[7] : _22_;
  assign o[7] = d[0] ? i0[7] : _23_;
  assign _24_ = i3[8] & d[3];
  assign _25_ = d[2] ? i2[8] : _24_;
  assign _26_ = d[1] ? i1[8] : _25_;
  assign o[8] = d[0] ? i0[8] : _26_;
  assign _27_ = i3[9] & d[3];
  assign _28_ = d[2] ? i2[9] : _27_;
  assign _29_ = d[1] ? i1[9] : _28_;
  assign o[9] = d[0] ? i0[9] : _29_;
endmodule

(* src = "fifo.v:1" *)
module fifo(pkti, we, full, pkto, re, empty, clk, rst);
  (* src = "fifo.v:5" *)
  wire [3:0] _000_;
  (* src = "fifo.v:5" *)
  wire [3:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  (* src = "fifo.v:2" *)
  input clk;
  (* src = "fifo.v:2" *)
  output empty;
  (* src = "fifo.v:2" *)
  output full;
  (* src = "fifo.v:4" *)
  reg [3:0] head;
  reg [9:0] \mem[0] ;
  reg [9:0] \mem[10] ;
  reg [9:0] \mem[11] ;
  reg [9:0] \mem[12] ;
  reg [9:0] \mem[13] ;
  reg [9:0] \mem[14] ;
  reg [9:0] \mem[15] ;
  reg [9:0] \mem[1] ;
  reg [9:0] \mem[2] ;
  reg [9:0] \mem[3] ;
  reg [9:0] \mem[4] ;
  reg [9:0] \mem[5] ;
  reg [9:0] \mem[6] ;
  reg [9:0] \mem[7] ;
  reg [9:0] \mem[8] ;
  reg [9:0] \mem[9] ;
  (* src = "fifo.v:1" *)
  input [9:0] pkti;
  (* src = "fifo.v:2" *)
  output [9:0] pkto;
  (* src = "fifo.v:2" *)
  input re;
  (* src = "fifo.v:2" *)
  input rst;
  (* src = "fifo.v:4" *)
  reg [3:0] tail;
  (* src = "fifo.v:1" *)
  input we;
  assign _162_ = ~(tail[0] ^ head[0]);
  assign _163_ = tail[1] ^ head[1];
  assign _164_ = _163_ | ~(_162_);
  assign _165_ = ~(tail[2] ^ head[2]);
  assign _166_ = tail[3] ^ head[3];
  assign _167_ = _166_ | ~(_165_);
  assign empty = ~(_167_ | _164_);
  assign _168_ = tail[0] ^ head[0];
  assign _169_ = head[0] & ~(head[1]);
  assign _170_ = head[1] & ~(head[0]);
  assign _171_ = _170_ | _169_;
  assign _172_ = _171_ ^ tail[1];
  assign _173_ = _172_ | ~(_168_);
  assign _174_ = ~head[2];
  assign _175_ = head[1] & head[0];
  assign _176_ = ~(_175_ ^ _174_);
  assign _177_ = ~(_176_ ^ tail[2]);
  assign _178_ = ~tail[3];
  assign _179_ = _175_ & ~(_174_);
  assign _180_ = _179_ ^ head[3];
  assign _181_ = ~(_180_ ^ _178_);
  assign _182_ = _181_ | ~(_177_);
  assign full = ~(_182_ | _173_);
  assign _183_ = tail[0] ? \mem[1] [0] : \mem[0] [0];
  assign _184_ = tail[0] ? \mem[3] [0] : \mem[2] [0];
  assign _185_ = tail[1] ? _184_ : _183_;
  assign _186_ = tail[0] ? \mem[5] [0] : \mem[4] [0];
  assign _187_ = tail[0] ? \mem[7] [0] : \mem[6] [0];
  assign _188_ = tail[1] ? _187_ : _186_;
  assign _189_ = tail[2] ? _188_ : _185_;
  assign _190_ = tail[0] ? \mem[9] [0] : \mem[8] [0];
  assign _191_ = tail[0] ? \mem[11] [0] : \mem[10] [0];
  assign _192_ = tail[1] ? _191_ : _190_;
  assign _193_ = tail[0] ? \mem[13] [0] : \mem[12] [0];
  assign _194_ = tail[0] ? \mem[15] [0] : \mem[14] [0];
  assign _195_ = tail[1] ? _194_ : _193_;
  assign _196_ = tail[2] ? _195_ : _192_;
  assign _197_ = tail[3] ? _196_ : _189_;
  assign pkto[0] = _197_ & ~(empty);
  assign _198_ = tail[0] ? \mem[1] [1] : \mem[0] [1];
  assign _199_ = tail[0] ? \mem[3] [1] : \mem[2] [1];
  assign _200_ = tail[1] ? _199_ : _198_;
  assign _201_ = tail[0] ? \mem[5] [1] : \mem[4] [1];
  assign _202_ = tail[0] ? \mem[7] [1] : \mem[6] [1];
  assign _203_ = tail[1] ? _202_ : _201_;
  assign _204_ = tail[2] ? _203_ : _200_;
  assign _205_ = tail[0] ? \mem[9] [1] : \mem[8] [1];
  assign _206_ = tail[0] ? \mem[11] [1] : \mem[10] [1];
  assign _207_ = tail[1] ? _206_ : _205_;
  assign _208_ = tail[0] ? \mem[13] [1] : \mem[12] [1];
  assign _209_ = tail[0] ? \mem[15] [1] : \mem[14] [1];
  assign _210_ = tail[1] ? _209_ : _208_;
  assign _211_ = tail[2] ? _210_ : _207_;
  assign _212_ = tail[3] ? _211_ : _204_;
  assign pkto[1] = _212_ & ~(empty);
  assign _213_ = tail[0] ? \mem[1] [2] : \mem[0] [2];
  assign _214_ = tail[0] ? \mem[3] [2] : \mem[2] [2];
  assign _215_ = tail[1] ? _214_ : _213_;
  assign _216_ = tail[0] ? \mem[5] [2] : \mem[4] [2];
  assign _217_ = tail[0] ? \mem[7] [2] : \mem[6] [2];
  assign _218_ = tail[1] ? _217_ : _216_;
  assign _219_ = tail[2] ? _218_ : _215_;
  assign _220_ = tail[0] ? \mem[9] [2] : \mem[8] [2];
  assign _221_ = tail[0] ? \mem[11] [2] : \mem[10] [2];
  assign _222_ = tail[1] ? _221_ : _220_;
  assign _223_ = tail[0] ? \mem[13] [2] : \mem[12] [2];
  assign _224_ = tail[0] ? \mem[15] [2] : \mem[14] [2];
  assign _225_ = tail[1] ? _224_ : _223_;
  assign _226_ = tail[2] ? _225_ : _222_;
  assign _227_ = tail[3] ? _226_ : _219_;
  assign pkto[2] = _227_ & ~(empty);
  assign _228_ = tail[0] ? \mem[1] [3] : \mem[0] [3];
  assign _229_ = tail[0] ? \mem[3] [3] : \mem[2] [3];
  assign _230_ = tail[1] ? _229_ : _228_;
  assign _231_ = tail[0] ? \mem[5] [3] : \mem[4] [3];
  assign _232_ = tail[0] ? \mem[7] [3] : \mem[6] [3];
  assign _233_ = tail[1] ? _232_ : _231_;
  assign _234_ = tail[2] ? _233_ : _230_;
  assign _235_ = tail[0] ? \mem[9] [3] : \mem[8] [3];
  assign _236_ = tail[0] ? \mem[11] [3] : \mem[10] [3];
  assign _237_ = tail[1] ? _236_ : _235_;
  assign _238_ = tail[0] ? \mem[13] [3] : \mem[12] [3];
  assign _239_ = tail[0] ? \mem[15] [3] : \mem[14] [3];
  assign _240_ = tail[1] ? _239_ : _238_;
  assign _241_ = tail[2] ? _240_ : _237_;
  assign _242_ = tail[3] ? _241_ : _234_;
  assign pkto[3] = _242_ & ~(empty);
  assign _243_ = tail[0] ? \mem[1] [4] : \mem[0] [4];
  assign _244_ = tail[0] ? \mem[3] [4] : \mem[2] [4];
  assign _245_ = tail[1] ? _244_ : _243_;
  assign _246_ = tail[0] ? \mem[5] [4] : \mem[4] [4];
  assign _247_ = tail[0] ? \mem[7] [4] : \mem[6] [4];
  assign _248_ = tail[1] ? _247_ : _246_;
  assign _249_ = tail[2] ? _248_ : _245_;
  assign _250_ = tail[0] ? \mem[9] [4] : \mem[8] [4];
  assign _251_ = tail[0] ? \mem[11] [4] : \mem[10] [4];
  assign _252_ = tail[1] ? _251_ : _250_;
  assign _253_ = tail[0] ? \mem[13] [4] : \mem[12] [4];
  assign _254_ = tail[0] ? \mem[15] [4] : \mem[14] [4];
  assign _255_ = tail[1] ? _254_ : _253_;
  assign _256_ = tail[2] ? _255_ : _252_;
  assign _257_ = tail[3] ? _256_ : _249_;
  assign pkto[4] = _257_ & ~(empty);
  assign _258_ = tail[0] ? \mem[1] [5] : \mem[0] [5];
  assign _259_ = tail[0] ? \mem[3] [5] : \mem[2] [5];
  assign _260_ = tail[1] ? _259_ : _258_;
  assign _261_ = tail[0] ? \mem[5] [5] : \mem[4] [5];
  assign _262_ = tail[0] ? \mem[7] [5] : \mem[6] [5];
  assign _263_ = tail[1] ? _262_ : _261_;
  assign _264_ = tail[2] ? _263_ : _260_;
  assign _265_ = tail[0] ? \mem[9] [5] : \mem[8] [5];
  assign _266_ = tail[0] ? \mem[11] [5] : \mem[10] [5];
  assign _267_ = tail[1] ? _266_ : _265_;
  assign _268_ = tail[0] ? \mem[13] [5] : \mem[12] [5];
  assign _269_ = tail[0] ? \mem[15] [5] : \mem[14] [5];
  assign _270_ = tail[1] ? _269_ : _268_;
  assign _271_ = tail[2] ? _270_ : _267_;
  assign _272_ = tail[3] ? _271_ : _264_;
  assign pkto[5] = _272_ & ~(empty);
  assign _273_ = tail[0] ? \mem[1] [6] : \mem[0] [6];
  assign _274_ = tail[0] ? \mem[3] [6] : \mem[2] [6];
  assign _275_ = tail[1] ? _274_ : _273_;
  assign _276_ = tail[0] ? \mem[5] [6] : \mem[4] [6];
  assign _277_ = tail[0] ? \mem[7] [6] : \mem[6] [6];
  assign _278_ = tail[1] ? _277_ : _276_;
  assign _279_ = tail[2] ? _278_ : _275_;
  assign _280_ = tail[0] ? \mem[9] [6] : \mem[8] [6];
  assign _281_ = tail[0] ? \mem[11] [6] : \mem[10] [6];
  assign _282_ = tail[1] ? _281_ : _280_;
  assign _283_ = tail[0] ? \mem[13] [6] : \mem[12] [6];
  assign _284_ = tail[0] ? \mem[15] [6] : \mem[14] [6];
  assign _285_ = tail[1] ? _284_ : _283_;
  assign _286_ = tail[2] ? _285_ : _282_;
  assign _287_ = tail[3] ? _286_ : _279_;
  assign pkto[6] = _287_ & ~(empty);
  assign _288_ = tail[0] ? \mem[1] [7] : \mem[0] [7];
  assign _289_ = tail[0] ? \mem[3] [7] : \mem[2] [7];
  assign _290_ = tail[1] ? _289_ : _288_;
  assign _291_ = tail[0] ? \mem[5] [7] : \mem[4] [7];
  assign _292_ = tail[0] ? \mem[7] [7] : \mem[6] [7];
  assign _293_ = tail[1] ? _292_ : _291_;
  assign _294_ = tail[2] ? _293_ : _290_;
  assign _295_ = tail[0] ? \mem[9] [7] : \mem[8] [7];
  assign _296_ = tail[0] ? \mem[11] [7] : \mem[10] [7];
  assign _297_ = tail[1] ? _296_ : _295_;
  assign _298_ = tail[0] ? \mem[13] [7] : \mem[12] [7];
  assign _299_ = tail[0] ? \mem[15] [7] : \mem[14] [7];
  assign _300_ = tail[1] ? _299_ : _298_;
  assign _301_ = tail[2] ? _300_ : _297_;
  assign _302_ = tail[3] ? _301_ : _294_;
  assign pkto[7] = _302_ & ~(empty);
  assign _303_ = tail[0] ? \mem[1] [8] : \mem[0] [8];
  assign _304_ = tail[0] ? \mem[3] [8] : \mem[2] [8];
  assign _305_ = tail[1] ? _304_ : _303_;
  assign _306_ = tail[0] ? \mem[5] [8] : \mem[4] [8];
  assign _307_ = tail[0] ? \mem[7] [8] : \mem[6] [8];
  assign _308_ = tail[1] ? _307_ : _306_;
  assign _309_ = tail[2] ? _308_ : _305_;
  assign _310_ = tail[0] ? \mem[9] [8] : \mem[8] [8];
  assign _311_ = tail[0] ? \mem[11] [8] : \mem[10] [8];
  assign _312_ = tail[1] ? _311_ : _310_;
  assign _313_ = tail[0] ? \mem[13] [8] : \mem[12] [8];
  assign _314_ = tail[0] ? \mem[15] [8] : \mem[14] [8];
  assign _315_ = tail[1] ? _314_ : _313_;
  assign _316_ = tail[2] ? _315_ : _312_;
  assign _317_ = tail[3] ? _316_ : _309_;
  assign pkto[8] = _317_ & ~(empty);
  assign _318_ = tail[0] ? \mem[1] [9] : \mem[0] [9];
  assign _319_ = tail[0] ? \mem[3] [9] : \mem[2] [9];
  assign _320_ = tail[1] ? _319_ : _318_;
  assign _321_ = tail[0] ? \mem[5] [9] : \mem[4] [9];
  assign _322_ = tail[0] ? \mem[7] [9] : \mem[6] [9];
  assign _323_ = tail[1] ? _322_ : _321_;
  assign _324_ = tail[2] ? _323_ : _320_;
  assign _325_ = tail[0] ? \mem[9] [9] : \mem[8] [9];
  assign _326_ = tail[0] ? \mem[11] [9] : \mem[10] [9];
  assign _327_ = tail[1] ? _326_ : _325_;
  assign _328_ = tail[0] ? \mem[13] [9] : \mem[12] [9];
  assign _329_ = tail[0] ? \mem[15] [9] : \mem[14] [9];
  assign _330_ = tail[1] ? _329_ : _328_;
  assign _331_ = tail[2] ? _330_ : _327_;
  assign _332_ = tail[3] ? _331_ : _324_;
  assign pkto[9] = _332_ & ~(empty);
  assign _000_[0] = we ^ head[0];
  assign _000_[1] = we ? _171_ : head[1];
  assign _000_[2] = we ? _176_ : head[2];
  assign _000_[3] = we ? _180_ : head[3];
  assign _001_[0] = re ^ tail[0];
  assign _333_ = tail[1] ^ tail[0];
  assign _001_[1] = re ? _333_ : tail[1];
  assign _334_ = ~(tail[1] & tail[0]);
  assign _335_ = ~(_334_ ^ tail[2]);
  assign _001_[2] = re ? _335_ : tail[2];
  assign _336_ = tail[2] & ~(_334_);
  assign _337_ = ~(_336_ ^ _178_);
  assign _001_[3] = re ? _337_ : tail[3];
  assign _338_ = ~(head[3] & head[2]);
  assign _339_ = _338_ | ~(_170_);
  assign _340_ = we & ~(_339_);
  assign _052_ = _340_ ? pkti[0] : \mem[14] [0];
  assign _053_ = _340_ ? pkti[1] : \mem[14] [1];
  assign _054_ = _340_ ? pkti[2] : \mem[14] [2];
  assign _055_ = _340_ ? pkti[3] : \mem[14] [3];
  assign _056_ = _340_ ? pkti[4] : \mem[14] [4];
  assign _057_ = _340_ ? pkti[5] : \mem[14] [5];
  assign _058_ = _340_ ? pkti[6] : \mem[14] [6];
  assign _059_ = _340_ ? pkti[7] : \mem[14] [7];
  assign _060_ = _340_ ? pkti[8] : \mem[14] [8];
  assign _061_ = _340_ ? pkti[9] : \mem[14] [9];
  assign _341_ = head[3] | ~(head[2]);
  assign _342_ = _341_ | ~(_169_);
  assign _343_ = _342_ | ~(we);
  assign _112_ = _343_ ? \mem[5] [0] : pkti[0];
  assign _113_ = _343_ ? \mem[5] [1] : pkti[1];
  assign _114_ = _343_ ? \mem[5] [2] : pkti[2];
  assign _115_ = _343_ ? \mem[5] [3] : pkti[3];
  assign _116_ = _343_ ? \mem[5] [4] : pkti[4];
  assign _117_ = _343_ ? \mem[5] [5] : pkti[5];
  assign _118_ = _343_ ? \mem[5] [6] : pkti[6];
  assign _119_ = _343_ ? \mem[5] [7] : pkti[7];
  assign _120_ = _343_ ? \mem[5] [8] : pkti[8];
  assign _121_ = _343_ ? \mem[5] [9] : pkti[9];
  assign _344_ = ~(head[1] | head[0]);
  assign _345_ = _341_ | ~(_344_);
  assign _346_ = _345_ | ~(we);
  assign _102_ = _346_ ? \mem[4] [0] : pkti[0];
  assign _103_ = _346_ ? \mem[4] [1] : pkti[1];
  assign _104_ = _346_ ? \mem[4] [2] : pkti[2];
  assign _105_ = _346_ ? \mem[4] [3] : pkti[3];
  assign _106_ = _346_ ? \mem[4] [4] : pkti[4];
  assign _107_ = _346_ ? \mem[4] [5] : pkti[5];
  assign _108_ = _346_ ? \mem[4] [6] : pkti[6];
  assign _109_ = _346_ ? \mem[4] [7] : pkti[7];
  assign _110_ = _346_ ? \mem[4] [8] : pkti[8];
  assign _111_ = _346_ ? \mem[4] [9] : pkti[9];
  assign _347_ = head[2] | ~(head[3]);
  assign _348_ = _347_ | ~(_344_);
  assign _349_ = _348_ | ~(we);
  assign _142_ = _349_ ? \mem[8] [0] : pkti[0];
  assign _143_ = _349_ ? \mem[8] [1] : pkti[1];
  assign _144_ = _349_ ? \mem[8] [2] : pkti[2];
  assign _145_ = _349_ ? \mem[8] [3] : pkti[3];
  assign _146_ = _349_ ? \mem[8] [4] : pkti[4];
  assign _147_ = _349_ ? \mem[8] [5] : pkti[5];
  assign _148_ = _349_ ? \mem[8] [6] : pkti[6];
  assign _149_ = _349_ ? \mem[8] [7] : pkti[7];
  assign _150_ = _349_ ? \mem[8] [8] : pkti[8];
  assign _151_ = _349_ ? \mem[8] [9] : pkti[9];
  assign _350_ = _338_ | ~(_169_);
  assign _351_ = _350_ | ~(we);
  assign _042_ = _351_ ? \mem[13] [0] : pkti[0];
  assign _043_ = _351_ ? \mem[13] [1] : pkti[1];
  assign _044_ = _351_ ? \mem[13] [2] : pkti[2];
  assign _045_ = _351_ ? \mem[13] [3] : pkti[3];
  assign _046_ = _351_ ? \mem[13] [4] : pkti[4];
  assign _047_ = _351_ ? \mem[13] [5] : pkti[5];
  assign _048_ = _351_ ? \mem[13] [6] : pkti[6];
  assign _049_ = _351_ ? \mem[13] [7] : pkti[7];
  assign _050_ = _351_ ? \mem[13] [8] : pkti[8];
  assign _051_ = _351_ ? \mem[13] [9] : pkti[9];
  assign _352_ = _341_ | ~(_175_);
  assign _353_ = _352_ | ~(we);
  assign _132_ = _353_ ? \mem[7] [0] : pkti[0];
  assign _133_ = _353_ ? \mem[7] [1] : pkti[1];
  assign _134_ = _353_ ? \mem[7] [2] : pkti[2];
  assign _135_ = _353_ ? \mem[7] [3] : pkti[3];
  assign _136_ = _353_ ? \mem[7] [4] : pkti[4];
  assign _137_ = _353_ ? \mem[7] [5] : pkti[5];
  assign _138_ = _353_ ? \mem[7] [6] : pkti[6];
  assign _139_ = _353_ ? \mem[7] [7] : pkti[7];
  assign _140_ = _353_ ? \mem[7] [8] : pkti[8];
  assign _141_ = _353_ ? \mem[7] [9] : pkti[9];
  assign _354_ = _341_ | ~(_170_);
  assign _355_ = _354_ | ~(we);
  assign _122_ = _355_ ? \mem[6] [0] : pkti[0];
  assign _123_ = _355_ ? \mem[6] [1] : pkti[1];
  assign _124_ = _355_ ? \mem[6] [2] : pkti[2];
  assign _125_ = _355_ ? \mem[6] [3] : pkti[3];
  assign _126_ = _355_ ? \mem[6] [4] : pkti[4];
  assign _127_ = _355_ ? \mem[6] [5] : pkti[5];
  assign _128_ = _355_ ? \mem[6] [6] : pkti[6];
  assign _129_ = _355_ ? \mem[6] [7] : pkti[7];
  assign _130_ = _355_ ? \mem[6] [8] : pkti[8];
  assign _131_ = _355_ ? \mem[6] [9] : pkti[9];
  assign _356_ = _338_ | ~(_344_);
  assign _357_ = _356_ | ~(we);
  assign _032_ = _357_ ? \mem[12] [0] : pkti[0];
  assign _033_ = _357_ ? \mem[12] [1] : pkti[1];
  assign _034_ = _357_ ? \mem[12] [2] : pkti[2];
  assign _035_ = _357_ ? \mem[12] [3] : pkti[3];
  assign _036_ = _357_ ? \mem[12] [4] : pkti[4];
  assign _037_ = _357_ ? \mem[12] [5] : pkti[5];
  assign _038_ = _357_ ? \mem[12] [6] : pkti[6];
  assign _039_ = _357_ ? \mem[12] [7] : pkti[7];
  assign _040_ = _357_ ? \mem[12] [8] : pkti[8];
  assign _041_ = _357_ ? \mem[12] [9] : pkti[9];
  assign _358_ = head[3] | head[2];
  assign _359_ = _358_ | ~(_175_);
  assign _360_ = _359_ | ~(we);
  assign _092_ = _360_ ? \mem[3] [0] : pkti[0];
  assign _093_ = _360_ ? \mem[3] [1] : pkti[1];
  assign _094_ = _360_ ? \mem[3] [2] : pkti[2];
  assign _095_ = _360_ ? \mem[3] [3] : pkti[3];
  assign _096_ = _360_ ? \mem[3] [4] : pkti[4];
  assign _097_ = _360_ ? \mem[3] [5] : pkti[5];
  assign _098_ = _360_ ? \mem[3] [6] : pkti[6];
  assign _099_ = _360_ ? \mem[3] [7] : pkti[7];
  assign _100_ = _360_ ? \mem[3] [8] : pkti[8];
  assign _101_ = _360_ ? \mem[3] [9] : pkti[9];
  assign _361_ = _347_ | ~(_175_);
  assign _362_ = _361_ | ~(we);
  assign _022_ = _362_ ? \mem[11] [0] : pkti[0];
  assign _023_ = _362_ ? \mem[11] [1] : pkti[1];
  assign _024_ = _362_ ? \mem[11] [2] : pkti[2];
  assign _025_ = _362_ ? \mem[11] [3] : pkti[3];
  assign _026_ = _362_ ? \mem[11] [4] : pkti[4];
  assign _027_ = _362_ ? \mem[11] [5] : pkti[5];
  assign _028_ = _362_ ? \mem[11] [6] : pkti[6];
  assign _029_ = _362_ ? \mem[11] [7] : pkti[7];
  assign _030_ = _362_ ? \mem[11] [8] : pkti[8];
  assign _031_ = _362_ ? \mem[11] [9] : pkti[9];
  assign _363_ = _358_ | ~(_170_);
  assign _364_ = _363_ | ~(we);
  assign _082_ = _364_ ? \mem[2] [0] : pkti[0];
  assign _083_ = _364_ ? \mem[2] [1] : pkti[1];
  assign _084_ = _364_ ? \mem[2] [2] : pkti[2];
  assign _085_ = _364_ ? \mem[2] [3] : pkti[3];
  assign _086_ = _364_ ? \mem[2] [4] : pkti[4];
  assign _087_ = _364_ ? \mem[2] [5] : pkti[5];
  assign _088_ = _364_ ? \mem[2] [6] : pkti[6];
  assign _089_ = _364_ ? \mem[2] [7] : pkti[7];
  assign _090_ = _364_ ? \mem[2] [8] : pkti[8];
  assign _091_ = _364_ ? \mem[2] [9] : pkti[9];
  assign _365_ = _347_ | ~(_170_);
  assign _366_ = _365_ | ~(we);
  assign _012_ = _366_ ? \mem[10] [0] : pkti[0];
  assign _013_ = _366_ ? \mem[10] [1] : pkti[1];
  assign _014_ = _366_ ? \mem[10] [2] : pkti[2];
  assign _015_ = _366_ ? \mem[10] [3] : pkti[3];
  assign _016_ = _366_ ? \mem[10] [4] : pkti[4];
  assign _017_ = _366_ ? \mem[10] [5] : pkti[5];
  assign _018_ = _366_ ? \mem[10] [6] : pkti[6];
  assign _019_ = _366_ ? \mem[10] [7] : pkti[7];
  assign _020_ = _366_ ? \mem[10] [8] : pkti[8];
  assign _021_ = _366_ ? \mem[10] [9] : pkti[9];
  assign _367_ = _358_ | ~(_344_);
  assign _368_ = _367_ | ~(we);
  assign _002_ = _368_ ? \mem[0] [0] : pkti[0];
  assign _003_ = _368_ ? \mem[0] [1] : pkti[1];
  assign _004_ = _368_ ? \mem[0] [2] : pkti[2];
  assign _005_ = _368_ ? \mem[0] [3] : pkti[3];
  assign _006_ = _368_ ? \mem[0] [4] : pkti[4];
  assign _007_ = _368_ ? \mem[0] [5] : pkti[5];
  assign _008_ = _368_ ? \mem[0] [6] : pkti[6];
  assign _009_ = _368_ ? \mem[0] [7] : pkti[7];
  assign _010_ = _368_ ? \mem[0] [8] : pkti[8];
  assign _011_ = _368_ ? \mem[0] [9] : pkti[9];
  assign _369_ = _358_ | ~(_169_);
  assign _370_ = _369_ | ~(we);
  assign _072_ = _370_ ? \mem[1] [0] : pkti[0];
  assign _073_ = _370_ ? \mem[1] [1] : pkti[1];
  assign _074_ = _370_ ? \mem[1] [2] : pkti[2];
  assign _075_ = _370_ ? \mem[1] [3] : pkti[3];
  assign _076_ = _370_ ? \mem[1] [4] : pkti[4];
  assign _077_ = _370_ ? \mem[1] [5] : pkti[5];
  assign _078_ = _370_ ? \mem[1] [6] : pkti[6];
  assign _079_ = _370_ ? \mem[1] [7] : pkti[7];
  assign _080_ = _370_ ? \mem[1] [8] : pkti[8];
  assign _081_ = _370_ ? \mem[1] [9] : pkti[9];
  assign _371_ = _338_ | ~(_175_);
  assign _372_ = _371_ | ~(we);
  assign _062_ = _372_ ? \mem[15] [0] : pkti[0];
  assign _063_ = _372_ ? \mem[15] [1] : pkti[1];
  assign _064_ = _372_ ? \mem[15] [2] : pkti[2];
  assign _065_ = _372_ ? \mem[15] [3] : pkti[3];
  assign _066_ = _372_ ? \mem[15] [4] : pkti[4];
  assign _067_ = _372_ ? \mem[15] [5] : pkti[5];
  assign _068_ = _372_ ? \mem[15] [6] : pkti[6];
  assign _069_ = _372_ ? \mem[15] [7] : pkti[7];
  assign _070_ = _372_ ? \mem[15] [8] : pkti[8];
  assign _071_ = _372_ ? \mem[15] [9] : pkti[9];
  assign _373_ = _347_ | ~(_169_);
  assign _374_ = _373_ | ~(we);
  assign _152_ = _374_ ? \mem[9] [0] : pkti[0];
  assign _153_ = _374_ ? \mem[9] [1] : pkti[1];
  assign _154_ = _374_ ? \mem[9] [2] : pkti[2];
  assign _155_ = _374_ ? \mem[9] [3] : pkti[3];
  assign _156_ = _374_ ? \mem[9] [4] : pkti[4];
  assign _157_ = _374_ ? \mem[9] [5] : pkti[5];
  assign _158_ = _374_ ? \mem[9] [6] : pkti[6];
  assign _159_ = _374_ ? \mem[9] [7] : pkti[7];
  assign _160_ = _374_ ? \mem[9] [8] : pkti[8];
  assign _161_ = _374_ ? \mem[9] [9] : pkti[9];
  always @(posedge clk)
      \mem[12] [0] <= _032_;
  always @(posedge clk)
      \mem[12] [1] <= _033_;
  always @(posedge clk)
      \mem[12] [2] <= _034_;
  always @(posedge clk)
      \mem[12] [3] <= _035_;
  always @(posedge clk)
      \mem[12] [4] <= _036_;
  always @(posedge clk)
      \mem[12] [5] <= _037_;
  always @(posedge clk)
      \mem[12] [6] <= _038_;
  always @(posedge clk)
      \mem[12] [7] <= _039_;
  always @(posedge clk)
      \mem[12] [8] <= _040_;
  always @(posedge clk)
      \mem[12] [9] <= _041_;
  always @(posedge clk)
      \mem[11] [0] <= _022_;
  always @(posedge clk)
      \mem[11] [1] <= _023_;
  always @(posedge clk)
      \mem[11] [2] <= _024_;
  always @(posedge clk)
      \mem[11] [3] <= _025_;
  always @(posedge clk)
      \mem[11] [4] <= _026_;
  always @(posedge clk)
      \mem[11] [5] <= _027_;
  always @(posedge clk)
      \mem[11] [6] <= _028_;
  always @(posedge clk)
      \mem[11] [7] <= _029_;
  always @(posedge clk)
      \mem[11] [8] <= _030_;
  always @(posedge clk)
      \mem[11] [9] <= _031_;
  always @(posedge clk)
      \mem[2] [0] <= _082_;
  always @(posedge clk)
      \mem[2] [1] <= _083_;
  always @(posedge clk)
      \mem[2] [2] <= _084_;
  always @(posedge clk)
      \mem[2] [3] <= _085_;
  always @(posedge clk)
      \mem[2] [4] <= _086_;
  always @(posedge clk)
      \mem[2] [5] <= _087_;
  always @(posedge clk)
      \mem[2] [6] <= _088_;
  always @(posedge clk)
      \mem[2] [7] <= _089_;
  always @(posedge clk)
      \mem[2] [8] <= _090_;
  always @(posedge clk)
      \mem[2] [9] <= _091_;
  always @(posedge clk)
      \mem[7] [0] <= _132_;
  always @(posedge clk)
      \mem[7] [1] <= _133_;
  always @(posedge clk)
      \mem[7] [2] <= _134_;
  always @(posedge clk)
      \mem[7] [3] <= _135_;
  always @(posedge clk)
      \mem[7] [4] <= _136_;
  always @(posedge clk)
      \mem[7] [5] <= _137_;
  always @(posedge clk)
      \mem[7] [6] <= _138_;
  always @(posedge clk)
      \mem[7] [7] <= _139_;
  always @(posedge clk)
      \mem[7] [8] <= _140_;
  always @(posedge clk)
      \mem[7] [9] <= _141_;
  always @(posedge clk)
      \mem[4] [0] <= _102_;
  always @(posedge clk)
      \mem[4] [1] <= _103_;
  always @(posedge clk)
      \mem[4] [2] <= _104_;
  always @(posedge clk)
      \mem[4] [3] <= _105_;
  always @(posedge clk)
      \mem[4] [4] <= _106_;
  always @(posedge clk)
      \mem[4] [5] <= _107_;
  always @(posedge clk)
      \mem[4] [6] <= _108_;
  always @(posedge clk)
      \mem[4] [7] <= _109_;
  always @(posedge clk)
      \mem[4] [8] <= _110_;
  always @(posedge clk)
      \mem[4] [9] <= _111_;
  always @(posedge clk)
      \mem[1] [0] <= _072_;
  always @(posedge clk)
      \mem[1] [1] <= _073_;
  always @(posedge clk)
      \mem[1] [2] <= _074_;
  always @(posedge clk)
      \mem[1] [3] <= _075_;
  always @(posedge clk)
      \mem[1] [4] <= _076_;
  always @(posedge clk)
      \mem[1] [5] <= _077_;
  always @(posedge clk)
      \mem[1] [6] <= _078_;
  always @(posedge clk)
      \mem[1] [7] <= _079_;
  always @(posedge clk)
      \mem[1] [8] <= _080_;
  always @(posedge clk)
      \mem[1] [9] <= _081_;
  always @(posedge clk)
      \mem[9] [0] <= _152_;
  always @(posedge clk)
      \mem[9] [1] <= _153_;
  always @(posedge clk)
      \mem[9] [2] <= _154_;
  always @(posedge clk)
      \mem[9] [3] <= _155_;
  always @(posedge clk)
      \mem[9] [4] <= _156_;
  always @(posedge clk)
      \mem[9] [5] <= _157_;
  always @(posedge clk)
      \mem[9] [6] <= _158_;
  always @(posedge clk)
      \mem[9] [7] <= _159_;
  always @(posedge clk)
      \mem[9] [8] <= _160_;
  always @(posedge clk)
      \mem[9] [9] <= _161_;
  always @(posedge clk)
      \mem[8] [0] <= _142_;
  always @(posedge clk)
      \mem[8] [1] <= _143_;
  always @(posedge clk)
      \mem[8] [2] <= _144_;
  always @(posedge clk)
      \mem[8] [3] <= _145_;
  always @(posedge clk)
      \mem[8] [4] <= _146_;
  always @(posedge clk)
      \mem[8] [5] <= _147_;
  always @(posedge clk)
      \mem[8] [6] <= _148_;
  always @(posedge clk)
      \mem[8] [7] <= _149_;
  always @(posedge clk)
      \mem[8] [8] <= _150_;
  always @(posedge clk)
      \mem[8] [9] <= _151_;
  always @(posedge clk)
      \mem[0] [0] <= _002_;
  always @(posedge clk)
      \mem[0] [1] <= _003_;
  always @(posedge clk)
      \mem[0] [2] <= _004_;
  always @(posedge clk)
      \mem[0] [3] <= _005_;
  always @(posedge clk)
      \mem[0] [4] <= _006_;
  always @(posedge clk)
      \mem[0] [5] <= _007_;
  always @(posedge clk)
      \mem[0] [6] <= _008_;
  always @(posedge clk)
      \mem[0] [7] <= _009_;
  always @(posedge clk)
      \mem[0] [8] <= _010_;
  always @(posedge clk)
      \mem[0] [9] <= _011_;
  always @(posedge clk)
      \mem[13] [0] <= _042_;
  always @(posedge clk)
      \mem[13] [1] <= _043_;
  always @(posedge clk)
      \mem[13] [2] <= _044_;
  always @(posedge clk)
      \mem[13] [3] <= _045_;
  always @(posedge clk)
      \mem[13] [4] <= _046_;
  always @(posedge clk)
      \mem[13] [5] <= _047_;
  always @(posedge clk)
      \mem[13] [6] <= _048_;
  always @(posedge clk)
      \mem[13] [7] <= _049_;
  always @(posedge clk)
      \mem[13] [8] <= _050_;
  always @(posedge clk)
      \mem[13] [9] <= _051_;
  always @(posedge clk)
      \mem[10] [0] <= _012_;
  always @(posedge clk)
      \mem[10] [1] <= _013_;
  always @(posedge clk)
      \mem[10] [2] <= _014_;
  always @(posedge clk)
      \mem[10] [3] <= _015_;
  always @(posedge clk)
      \mem[10] [4] <= _016_;
  always @(posedge clk)
      \mem[10] [5] <= _017_;
  always @(posedge clk)
      \mem[10] [6] <= _018_;
  always @(posedge clk)
      \mem[10] [7] <= _019_;
  always @(posedge clk)
      \mem[10] [8] <= _020_;
  always @(posedge clk)
      \mem[10] [9] <= _021_;
  always @(posedge clk)
      \mem[14] [0] <= _052_;
  always @(posedge clk)
      \mem[14] [1] <= _053_;
  always @(posedge clk)
      \mem[14] [2] <= _054_;
  always @(posedge clk)
      \mem[14] [3] <= _055_;
  always @(posedge clk)
      \mem[14] [4] <= _056_;
  always @(posedge clk)
      \mem[14] [5] <= _057_;
  always @(posedge clk)
      \mem[14] [6] <= _058_;
  always @(posedge clk)
      \mem[14] [7] <= _059_;
  always @(posedge clk)
      \mem[14] [8] <= _060_;
  always @(posedge clk)
      \mem[14] [9] <= _061_;
  always @(posedge clk)
      \mem[15] [0] <= _062_;
  always @(posedge clk)
      \mem[15] [1] <= _063_;
  always @(posedge clk)
      \mem[15] [2] <= _064_;
  always @(posedge clk)
      \mem[15] [3] <= _065_;
  always @(posedge clk)
      \mem[15] [4] <= _066_;
  always @(posedge clk)
      \mem[15] [5] <= _067_;
  always @(posedge clk)
      \mem[15] [6] <= _068_;
  always @(posedge clk)
      \mem[15] [7] <= _069_;
  always @(posedge clk)
      \mem[15] [8] <= _070_;
  always @(posedge clk)
      \mem[15] [9] <= _071_;
  always @(posedge clk)
      \mem[6] [0] <= _122_;
  always @(posedge clk)
      \mem[6] [1] <= _123_;
  always @(posedge clk)
      \mem[6] [2] <= _124_;
  always @(posedge clk)
      \mem[6] [3] <= _125_;
  always @(posedge clk)
      \mem[6] [4] <= _126_;
  always @(posedge clk)
      \mem[6] [5] <= _127_;
  always @(posedge clk)
      \mem[6] [6] <= _128_;
  always @(posedge clk)
      \mem[6] [7] <= _129_;
  always @(posedge clk)
      \mem[6] [8] <= _130_;
  always @(posedge clk)
      \mem[6] [9] <= _131_;
  always @(posedge clk)
      \mem[3] [0] <= _092_;
  always @(posedge clk)
      \mem[3] [1] <= _093_;
  always @(posedge clk)
      \mem[3] [2] <= _094_;
  always @(posedge clk)
      \mem[3] [3] <= _095_;
  always @(posedge clk)
      \mem[3] [4] <= _096_;
  always @(posedge clk)
      \mem[3] [5] <= _097_;
  always @(posedge clk)
      \mem[3] [6] <= _098_;
  always @(posedge clk)
      \mem[3] [7] <= _099_;
  always @(posedge clk)
      \mem[3] [8] <= _100_;
  always @(posedge clk)
      \mem[3] [9] <= _101_;
  always @(posedge clk)
      \mem[5] [0] <= _112_;
  always @(posedge clk)
      \mem[5] [1] <= _113_;
  always @(posedge clk)
      \mem[5] [2] <= _114_;
  always @(posedge clk)
      \mem[5] [3] <= _115_;
  always @(posedge clk)
      \mem[5] [4] <= _116_;
  always @(posedge clk)
      \mem[5] [5] <= _117_;
  always @(posedge clk)
      \mem[5] [6] <= _118_;
  always @(posedge clk)
      \mem[5] [7] <= _119_;
  always @(posedge clk)
      \mem[5] [8] <= _120_;
  always @(posedge clk)
      \mem[5] [9] <= _121_;
  (* src = "fifo.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      tail[0] <= 0;
    else
      tail[0] <= _001_[0];
  (* src = "fifo.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      tail[1] <= 0;
    else
      tail[1] <= _001_[1];
  (* src = "fifo.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      tail[2] <= 0;
    else
      tail[2] <= _001_[2];
  (* src = "fifo.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      tail[3] <= 0;
    else
      tail[3] <= _001_[3];
  (* src = "fifo.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      head[0] <= 0;
    else
      head[0] <= _000_[0];
  (* src = "fifo.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      head[1] <= 0;
    else
      head[1] <= _000_[1];
  (* src = "fifo.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      head[2] <= 0;
    else
      head[2] <= _000_[2];
  (* src = "fifo.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      head[3] <= 0;
    else
      head[3] <= _000_[3];
endmodule

(* src = "ib.v:1" *)
module ib(pkti, pkto, req, ack, empty, full, clk, rst);
  (* src = "ib.v:1" *)
  input ack;
  (* src = "ib.v:2" *)
  input clk;
  (* src = "ib.v:2" *)
  output empty;
  (* src = "ib.v:2" *)
  output full;
  (* src = "ib.v:1" *)
  input [9:0] pkti;
  (* src = "ib.v:1" *)
  output [9:0] pkto;
  (* src = "ib.v:4" *)
  wire re;
  (* src = "ib.v:1" *)
  output [3:0] req;
  (* src = "ib.v:2" *)
  input rst;
  (* src = "ib.v:3" *)
  wire we;
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:4" *)
  fifo fifo (
    .clk(clk),
    .empty(empty),
    .full(full),
    .pkti(pkti),
    .pkto(pkto),
    .re(re),
    .rst(rst),
    .we(we)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:5" *)
  ibsm ibsm (
    .ack(ack),
    .clk(clk),
    .empty(empty),
    .pkto(pkto),
    .re(re),
    .req(req),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:3" *)
  mkwe mkwe (
    .pkti(pkti),
    .we(we)
  );
endmodule

(* src = "ibsm.v:1" *)
module ibsm(pkto, re, empty, req, ack, clk, rst);
  (* src = "ibsm.v:5" *)
  wire _00_;
  (* src = "ibsm.v:5" *)
  wire [3:0] _01_;
  (* src = "ibsm.v:5" *)
  wire [2:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  (* src = "ibsm.v:2" *)
  input ack;
  (* src = "ibsm.v:2" *)
  input clk;
  (* src = "ibsm.v:1" *)
  input empty;
  (* src = "ibsm.v:1" *)
  input [9:0] pkto;
  (* src = "ibsm.v:1" *)
  output re;
  reg re;
  (* src = "ibsm.v:2" *)
  output [3:0] req;
  reg [3:0] req;
  (* src = "ibsm.v:2" *)
  input rst;
  (* src = "ibsm.v:4" *)
  reg [2:0] state;
  assign _03_ = state[1] | state[2];
  assign _04_ = ~(_03_ | state[0]);
  assign _05_ = ~state[2];
  assign _06_ = ~state[1];
  assign _07_ = ~empty;
  assign _08_ = pkto[9] & pkto[8];
  assign _09_ = _08_ | ~(req[0]);
  assign _10_ = _09_ | ~(_07_);
  assign _11_ = pkto[1] | pkto[0];
  assign _12_ = ~((_10_ | _05_) & (_06_ | _11_));
  assign _01_[0] = _04_ ? req[0] : _12_;
  assign _13_ = _08_ | ~(req[1]);
  assign _14_ = _13_ | ~(_07_);
  assign _15_ = pkto[1] | ~(pkto[0]);
  assign _16_ = ~((_14_ | _05_) & (_06_ | _15_));
  assign _01_[1] = _04_ ? req[1] : _16_;
  assign _17_ = _08_ | ~(req[2]);
  assign _18_ = _17_ | ~(_07_);
  assign _19_ = pkto[0] | ~(pkto[1]);
  assign _20_ = ~((_18_ | _05_) & (_06_ | _19_));
  assign _01_[2] = _04_ ? req[2] : _20_;
  assign _21_ = _08_ | ~(req[3]);
  assign _22_ = _21_ | ~(_07_);
  assign _23_ = ~(pkto[1] & pkto[0]);
  assign _24_ = ~((_22_ | _05_) & (_06_ | _23_));
  assign _01_[3] = _04_ ? req[3] : _24_;
  assign _25_ = ~(_08_ | empty);
  assign _26_ = ~(_25_ & state[2]);
  assign _27_ = ack | ~(re);
  assign _28_ = ~((_27_ | _06_) & _26_);
  assign _00_ = _03_ ? _28_ : re;
  assign _29_ = ~((_08_ | empty) & state[2]);
  assign _30_ = pkto[9] & ~(pkto[8]);
  assign _31_ = _30_ | ~(state[0]);
  assign _02_[0] = ~((_31_ & _29_) | _04_);
  assign _32_ = state[1] & ~(ack);
  assign _33_ = ~((_30_ & state[0]) | _32_);
  assign _02_[1] = ~(_33_ | _04_);
  assign _34_ = ~(ack & state[1]);
  assign _02_[2] = ~((_34_ & _26_) | _04_);
  (* src = "ibsm.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      state[0] <= 1;
    else
      state[0] <= _02_[0];
  (* src = "ibsm.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      state[1] <= 0;
    else
      state[1] <= _02_[1];
  (* src = "ibsm.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      state[2] <= 0;
    else
      state[2] <= _02_[2];
  (* src = "ibsm.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      re <= 0;
    else
      re <= _00_;
  (* src = "ibsm.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      req[0] <= 0;
    else
      req[0] <= _01_[0];
  (* src = "ibsm.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      req[1] <= 0;
    else
      req[1] <= _01_[1];
  (* src = "ibsm.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      req[2] <= 0;
    else
      req[2] <= _01_[2];
  (* src = "ibsm.v:5" *)
  always @(posedge clk or posedge rst)
    if (rst)
      req[3] <= 0;
    else
      req[3] <= _01_[3];
endmodule

(* src = "mkwe.v:1" *)
module mkwe(pkti, we);
  (* src = "mkwe.v:1" *)
  input [9:0] pkti;
  (* src = "mkwe.v:1" *)
  output we;
  assign we = pkti[9] | pkti[8];
endmodule

(* top =  1  *)
(* src = "sw.v:1" *)
module sw(i0, i1, i2, i3, o0, o1, o2, o3, clk, rst);
  (* src = "sw.v:4" *)
  wire ack0;
  (* src = "sw.v:8" *)
  wire ack00;
  (* src = "sw.v:9" *)
  wire ack01;
  (* src = "sw.v:10" *)
  wire ack02;
  (* src = "sw.v:11" *)
  wire ack03;
  (* src = "sw.v:5" *)
  wire ack1;
  (* src = "sw.v:8" *)
  wire ack10;
  (* src = "sw.v:9" *)
  wire ack11;
  (* src = "sw.v:10" *)
  wire ack12;
  (* src = "sw.v:11" *)
  wire ack13;
  (* src = "sw.v:6" *)
  wire ack2;
  (* src = "sw.v:8" *)
  wire ack20;
  (* src = "sw.v:9" *)
  wire ack21;
  (* src = "sw.v:10" *)
  wire ack22;
  (* src = "sw.v:11" *)
  wire ack23;
  (* src = "sw.v:7" *)
  wire ack3;
  (* src = "sw.v:8" *)
  wire ack30;
  (* src = "sw.v:9" *)
  wire ack31;
  (* src = "sw.v:10" *)
  wire ack32;
  (* src = "sw.v:11" *)
  wire ack33;
  (* src = "sw.v:1" *)
  input clk;
  (* src = "sw.v:2" *)
  wire [9:0] co0;
  (* src = "sw.v:2" *)
  wire [9:0] co1;
  (* src = "sw.v:2" *)
  wire [9:0] co2;
  (* src = "sw.v:2" *)
  wire [9:0] co3;
  (* src = "sw.v:4" *)
  (* unused_bits = "0" *)
  wire empty0;
  (* src = "sw.v:5" *)
  (* unused_bits = "0" *)
  wire empty1;
  (* src = "sw.v:6" *)
  (* unused_bits = "0" *)
  wire empty2;
  (* src = "sw.v:7" *)
  (* unused_bits = "0" *)
  wire empty3;
  (* src = "sw.v:4" *)
  (* unused_bits = "0" *)
  wire full0;
  (* src = "sw.v:5" *)
  (* unused_bits = "0" *)
  wire full1;
  (* src = "sw.v:6" *)
  (* unused_bits = "0" *)
  wire full2;
  (* src = "sw.v:7" *)
  (* unused_bits = "0" *)
  wire full3;
  (* src = "sw.v:1" *)
  input [9:0] i0;
  (* src = "sw.v:1" *)
  input [9:0] i1;
  (* src = "sw.v:1" *)
  input [9:0] i2;
  (* src = "sw.v:1" *)
  input [9:0] i3;
  (* src = "sw.v:1" *)
  output [9:0] o0;
  (* src = "sw.v:1" *)
  output [9:0] o1;
  (* src = "sw.v:1" *)
  output [9:0] o2;
  (* src = "sw.v:1" *)
  output [9:0] o3;
  (* src = "sw.v:3" *)
  wire [3:0] req0;
  (* src = "sw.v:3" *)
  wire [3:0] req1;
  (* src = "sw.v:3" *)
  wire [3:0] req2;
  (* src = "sw.v:3" *)
  wire [3:0] req3;
  (* src = "sw.v:1" *)
  input rst;
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:8" *)
  ackor ackor0 (
    .ack(ack0),
    .ack0(ack00),
    .ack1(ack10),
    .ack2(ack20),
    .ack3(ack30)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:9" *)
  ackor ackor1 (
    .ack(ack1),
    .ack0(ack01),
    .ack1(ack11),
    .ack2(ack21),
    .ack3(ack31)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:10" *)
  ackor ackor2 (
    .ack(ack2),
    .ack0(ack02),
    .ack1(ack12),
    .ack2(ack22),
    .ack3(ack32)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:11" *)
  ackor ackor3 (
    .ack(ack3),
    .ack0(ack03),
    .ack1(ack13),
    .ack2(ack23),
    .ack3(ack33)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:12" *)
  arb arb0 (
    .ack0(ack00),
    .ack1(ack01),
    .ack2(ack02),
    .ack3(ack03),
    .clk(clk),
    .req0(req0[0]),
    .req1(req1[0]),
    .req2(req2[0]),
    .req3(req3[0]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:13" *)
  arb arb1 (
    .ack0(ack10),
    .ack1(ack11),
    .ack2(ack12),
    .ack3(ack13),
    .clk(clk),
    .req0(req0[1]),
    .req1(req1[1]),
    .req2(req2[1]),
    .req3(req3[1]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:14" *)
  arb arb2 (
    .ack0(ack20),
    .ack1(ack21),
    .ack2(ack22),
    .ack3(ack23),
    .clk(clk),
    .req0(req0[2]),
    .req1(req1[2]),
    .req2(req2[2]),
    .req3(req3[2]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:15" *)
  arb arb3 (
    .ack0(ack30),
    .ack1(ack31),
    .ack2(ack32),
    .ack3(ack33),
    .clk(clk),
    .req0(req0[3]),
    .req1(req1[3]),
    .req2(req2[3]),
    .req3(req3[3]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:16" *)
  cb cb (
    .d0({ ack03, ack02, ack01, ack00 }),
    .d1({ ack13, ack12, ack11, ack10 }),
    .d2({ ack23, ack22, ack21, ack20 }),
    .d3({ ack33, ack32, ack31, ack30 }),
    .i0(co0),
    .i1(co1),
    .i2(co2),
    .i3(co3),
    .o0(o0),
    .o1(o1),
    .o2(o2),
    .o3(o3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:4" *)
  ib ib0 (
    .ack(ack0),
    .clk(clk),
    .empty(empty0),
    .full(full0),
    .pkti(i0),
    .pkto(co0),
    .req(req0),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:5" *)
  ib ib1 (
    .ack(ack1),
    .clk(clk),
    .empty(empty1),
    .full(full1),
    .pkti(i1),
    .pkto(co1),
    .req(req1),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:6" *)
  ib ib2 (
    .ack(ack2),
    .clk(clk),
    .empty(empty2),
    .full(full2),
    .pkti(i2),
    .pkto(co2),
    .req(req2),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:7" *)
  ib ib3 (
    .ack(ack3),
    .clk(clk),
    .empty(empty3),
    .full(full3),
    .pkti(i3),
    .pkto(co3),
    .req(req3),
    .rst(rst)
  );
endmodule
